feature/controller-nav-support
jellyfin/jellyfin-uwp pull request #50
Opened 2024-12-17 05:24 UTC by IAmUser4574

2025-02-02 22:29 UTC, JPVenson commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
is there no way to do this event driven?

2025-02-02 22:55 UTC, IAmUser4574 commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
I'm similarly not a fan of polling the gamepad state. Unfortunately this is the only default way of interacting with the [gamepad class](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad).

I also attempted to use the `CoreWindow.KeyUp` event in the [Windows.UI.Core](https://learn.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow.keyup?view=winrt-26100) library that [a stackoverflow user suggested](https://stackoverflow.com/questions/41811735/how-to-detect-game-controller-button-presses-abxy-in-uwp-apps) but I've experienced no luck on that potential solution with this project.

2025-02-03 05:31 UTC, JPVenson requested changes

2025-02-03 05:31 UTC, JPVenson commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
OK then atleast do those 3 things:
- Dispose the Dispatcher timer properly
- Set the DispatcherPriority.Input
- differentiate input sources and also make button detection time based, not interval based

2025-02-05 02:36 UTC, IAmUser4574 commented
@JPVenson thank you for your review! I have a few clarifying questions before making the changes:

> Dispose the Dispatcher timer properly

`DispatcherTimer` does not implement `IDisposable` - but I can implement `IDisposable` in the page code-behind and then `Stop` the timer and unregister the `Tick` event handler. Is that sufficient?

> Set the DispatcherPriority.Input

`System.Windows.Threading.DispatcherPriority` does not appear supported in UWP - but `DispatcherQueuePriority` is available and I can enqueue the gamepad input processing work via `DispatcherQueue` with `Low`, `Normal`, or `High` `DispatcherQueuePriority`.

> differentiate input sources

This is a good feature! I assume this would be differentiating tracked gamepad input state between multiple gamepads.

> make button detection time based, not interval based

Is the idea for this request that a successful click is only acted upon if the 'down' and 'up' actions are detected within a certain timespan? Out of curiosity, I performed some tests on other popular UWP Xbox apps (YouTube, Settings, etc) and found that they all allowed button actions to continue even if the 'down' and 'up' actions were many seconds apart. So the all seem to be using an "interval-based" approach. 

One change we can also discuss is whether to perform an action on button down *or* on button up. The apps I tested were not consistent on a convention.

2025-02-16 09:32 UTC, JPVenson approved these changes

2025-03-04 11:42 UTC, JPVenson commented
@TimGels pls test at your disgression

2025-03-16 13:22 UTC, TimGels approved these changes
Works during my testing with the xbox controller.

2025-03-16 20:55 UTC, merged

2025-03-28 04:43 UTC, dfederm commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
You can make this even driven. Instead of using Gamepad, you should do something more along the lines of this:

```cs
        Window.Current.CoreWindow.Dispatcher.AcceleratorKeyActivated += AcceleratorKeyActivated;

       /// ...

    /// <summary>
    /// Invoked on every keystroke, including system keys such as Alt key combinations, when
    /// this page is active and occupies the entire window.  Used to detect keyboard navigation
    /// between pages even when the page itself doesn't have focus.
    /// </summary>
    /// <param name="sender">Instance that triggered the event.</param>
    /// <param name="e">Event data describing the conditions that led to the event.</param>
    private void AcceleratorKeyActivated(CoreDispatcher sender, AcceleratorKeyEventArgs e)
    {
        var virtualKey = e.VirtualKey;

        // Only investigate further when Left, Right, or the dedicated Previous or Next keys
        // are pressed
        if ((e.EventType == CoreAcceleratorKeyEventType.SystemKeyDown
            || e.EventType == CoreAcceleratorKeyEventType.KeyDown) &&
            (
            virtualKey == VirtualKey.Left || virtualKey == VirtualKey.Right
            || virtualKey == VirtualKey.GoBack || virtualKey == VirtualKey.GoForward
            )
            )
        {
            var coreWindow = Window.Current.CoreWindow;
            var downState = CoreVirtualKeyStates.Down;
            bool menuKey = (coreWindow.GetKeyState(VirtualKey.Menu) & downState) == downState;
            bool controlKey = (coreWindow.GetKeyState(VirtualKey.Control) & downState) == downState;
            bool shiftKey = (coreWindow.GetKeyState(VirtualKey.Shift) & downState) == downState;
            bool noModifiers = !menuKey && !controlKey && !shiftKey;
            bool onlyAlt = menuKey && !controlKey && !shiftKey;

            if ((virtualKey == VirtualKey.GoBack && noModifiers) || (virtualKey == VirtualKey.Left && onlyAlt))
            {
                e.Handled = GoBack();
            }
            else if ((virtualKey == VirtualKey.GoForward && noModifiers) || (virtualKey == VirtualKey.Right && onlyAlt))
            {
                e.Handled = GoForward();
            }
        }
    }
```

ie, the B button behaves as `VirtualKey.GoBack`

2025-03-28 08:13 UTC, JPVenson commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
@IAmUser4574 if you could implement that too that would be awesome

2025-03-29 16:39 UTC, IAmUser4574 commented on Jellyfin/Controls/JellyfinWebView.xaml.cs
> +            _gamepadPollingtimer = new DispatcherTimer();
Thanks, I will take a look at this!